on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk
      options: -v ${PWD}:/src
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: make Makefile
