on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk:latest
    name: build
    steps:
      - uses: actions/checkout@v2
        with:
          repository: chris-y/zmakebas
      - name: build_zmakebas
        id: build_zmakebas
        run: make -f Makefile zmakebas
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas
          path: ./zmakebas
      - uses: actions/checkout@v2
      - name: Download zmakebas
        uses: actions/download-artifact@v1
        with:
          name: zmakebas
      - name: build
        id: build
        run: |
          chmod a+x ./zmakebas/zmakebas
          make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: TZX2TAP
          path: ./TZX2TAP
      - uses: actions/upload-artifact@v1
        with:
          name: tzxconv.bas
          path: ./tzxconv.bas
