on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk
#      options: -v ${PWD}:/src
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: |
          cd $GITHUB_WORKSPACE
          ls -la
          make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: TZX2TAP
