on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk:latest
    name: build
    steps:
      - uses: actions/checkout@v2
        with:
          name: chris-y/zmakebas
          ref: v1.5.2
      - name: build_zmakebas
        id: build_zmakebas
        run: ls -la
        #make -f Makefile zmakebas
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: TZX2TAP
          path: ./TZX2TAP
      - uses: actions/upload-artifact@v1
        with:
          name: tzxconv.bas
          path: ./tzxconv.bas
