on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: z88dk/z88dk:latest
#      options: -v ${PWD}:/src
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: TZX2TAP
          path: ./TZX2TAP
